/* gulpfile.js */

/**
 * Import uswds-compile
 */
import uswds from "@uswds/compile";

/**
 * USWDS version
 * Set the major version of USWDS you're using
 * (Current options are the numbers 2 or 3)
 */
uswds.settings.version = 3;

/**
 * Path settings
 * Default values for version 3.X
 *
 * https://designsystem.digital.gov/documentation/getting-started/developers/phase-two-compile/#step-5-customize-path-settings-2
 */

// Source location of the uswds package
uswds.paths.src.uswds = "./node_modules/@uswds";

// Source location of the USWDS Sass
uswds.paths.src.sass = "./node_modules/@uswds/uswds/packages";

// Source location of the USWDS theme files (Sass entry point and starter settings files)
uswds.paths.src.theme = "./node_modules/@uswds/uswds/dist/theme";

// Source location of the USWDS fonts
uswds.paths.src.fonts = "./node_modules/@uswds/uswds/dist/fonts";

// Source location of the USWDS images
uswds.paths.src.img = "./node_modules/@uswds/uswds/dist/img";

// Source location of the USWDS compiled JavaScript files
uswds.paths.src.js = "./node_modules/@uswds/uswds/dist/js";

// Source location of any existing project Sass files outside of paths.dist.theme.
// The watch script will watch this directory for changes.
uswds.paths.src.projectSass = "./styles";

// Source location of any additional project icons to include in the icon sprite.
// (Use only these project icons in the sprite by setting sprite.projectIconsOnly to true.)
uswds.paths.src.projectIcons = "./public/icons";

// Project destination for theme files (Sass entry point and settings)
uswds.paths.dist.theme = "./styles";

// Project destination for images
uswds.paths.dist.img = "./public/images";

// Project destination for fonts
uswds.paths.dist.fonts = "./public/fonts";

// Project destination for compiled JavaScript
uswds.paths.dist.js = "./public/uswds/js";

// Project destination for compiled CSS
uswds.paths.dist.css = "./public/css";

// Include only the icons in paths.src.projectIcons in the icon sprite
uswds.sprite.projectIconsOnly = false;

// Define the browserslist query for CSS prefixes generated by autoprefixer.
uswds.settings.compile.browserslist = [
  "> 2%",
  "last 2 versions",
  "IE 11",
  "not dead",
];

// Include sourcemap when compiling SASS to CSS.
uswds.settings.compile.sassSourcemaps = true;

// Show USWDS Sass deprecation warnings. When set to true, Sass will output deprecation
// warnings for USWDS code in the terminal during compilation. Deprecation warnings for non-USWDS
// Sass will output even when this value is set to false.
uswds.settings.compile.sassDeprecationWarnings = true;

/**
 * Exports
 * Add as many as you need
 */

// Run `npx gulp init`
export const init = uswds.init;
// Copy USWDS theme files (Sass entry point and settings files)
// from the `uswds` package to                               `paths.dist.theme`
//
// Copies all static assets: copyFonts + copyImages + copyJS
//      - `copyFonts`   - Copy USWDS fonts to                `paths.dist.fonts`
//      - `copyImages`  - Copy USWDS images to               `paths.dist.img`
//      - `copyJS`      - Copy USWDS compiled JavaScript to  `paths.dist.js`
//
// Compile Sass into                                         `paths.dist.css`
//
// Build the USWDS icon sprite into                          `paths.dist.img`

// Run `npx gulp compile`
export const compile = uswds.compile;
// Compile Sass into                                         `paths.dist.css`,
// Then build the USWDS icon sprite into                     `paths.dist.img`

// Run `npx gulp watch`
export const watch = uswds.watch;
// Compiles, then recompiles when there are changes to Sass files in
//                                                           `paths.dist.theme`
//                                                           `paths.src.projectSass`
